language: python

python: "2.7"

install:
    - pip install psycopg2
    - cp buildout/* .
    - cp database.cfg.example database.cfg
    - mkdir -p buildout-cache/eggs
    - mkdir -p buildout-cache/downloads
    - python bootstrap.py -c travis.cfg --setuptools-version=7.0 --version=2.2.5
    - bin/buildout -N -t 3 -c travis.cfg

script: bin/coverage run bin/test -s seantis.reservation

after_success:
    - pip install coveralls
    - coveralls
